"""Correction in the relationship of books and novelists

Revision ID: 93db94c90097
Revises: e8959f899ee1
Create Date: 2025-10-14 22:37:42.026963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93db94c90097'
down_revision: Union[str, Sequence[str], None] = 'e8959f899ee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('id_novelist', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'books', 'novelists', ['id_novelist'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'id_novelist')
    # ### end Alembic commands ###
