"""ajusts in Books model

Revision ID: ab6afa01e231
Revises: 3abaad263535
Create Date: 2025-10-21 16:57:11.980405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6afa01e231'
down_revision: Union[str, Sequence[str], None] = '3abaad263535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'year',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='EXTRACT(year FROM year)::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'year',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=False,
               postgresql_using="TO_DATE(year::text, 'YYYY')")
    # ### end Alembic commands ###
